### ISSUE TITLE
Doesnt work in new version of Time Doctor

### ISSUE THREAD

**Issue by rochiey** [piotrwest/TimeDoctorObfuscator#4]
Haven't seen any "options" in the new time doctor app. Just a user setting

**Comment by piotrwest** [comment]
This repo wasn't updated for a long time. Probably it doesn't work with the newest time doctor version. Please feel free to submit pull request if you will update it.

**Comment by rochiey** [comment]
Is it okay that my timedoctor says offline? i am worried that my time wont register in the website because its offline. i think this is because of the 127.0.0.1 in the proxy settings. Also do I run timedoctorobfuscator.exe and install fiddlecore everytime before running time doctor app?

**Comment by piotrwest** [comment]
I think it should say online. You should run timedoctorobfuscator.exe every time before running time doctor app. Indeed, you should put 127.0.0.1 as the proxy - that's how it works - TimeDoctorObfuscator is acting as a proxy.

**Comment by rochiey** [comment]
I love your enthusiasm in replying. One more question before I close this thread, if i put my normal timedoctor work screenshot and put it in compressedcats folder, should the timedoctorobfuscator upload the screenshot that ive replaced the cats wallpaper on?

**Comment by rochiey** [comment]
I found out and that it doesnt upload screenshots to the web after testing in 1 hr.

**Comment by rochiey** [comment]
Sorry found out that my time doctor version doesnt have screenshot feature version 2.2. Trying 2.3.49 version now. I hope it will upload. If it is then I'll close this thread. I'll update you.

**Comment by piotrwest** [comment]
Did you manage to make it work for yourself? If so, do you have any hints for other people?

**Comment by rochiey** [comment]
It works now, I suggest that people would download 2.3.40 or above version of timedoctor and below version 3, because 2.3.40 has screenshot. But the downside is that in 2.3.40, you cant control if the screenshot will show on screen. Regardless, it will upload a screenshot of your sweet-cat-wallpaper to the server. just replace the cat pictures with your normal work screenshot. However, the time will be obvious since it will randomly pick pictures in the cat wallpaper folder. Say you are working in 1pm and then the uploaded pic that is from your cat wallpaper has a time of 8am then your employer will be confused. Of course if they aren't technical enough then youll be fine. Nice!
